---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-dev-db
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: jelastic-dynamic-volume

