apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-02T08:59:37Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2023-08-25T16:17:20Z"
  generateName: econsulat-postgresql-
  labels:
    app: econsulatbusiness-postgresql
    chart: postgresql-6.5.9
    controller-revision-hash: econsulat-postgresql-59d48bd566
    heritage: Helm
    release: econsulat
    role: master
    statefulset.kubernetes.io/pod-name: econsulat-postgresql-0
  name: econsulat-postgresql-0
  namespace: qa
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: econsulat-postgresql
    uid: 1d4dc689-af7d-4831-b52b-b9d7332ca33e
  resourceVersion: "15074900"
  uid: bacd7120-5b65-4f83-811d-f3aa8e2d2a2c
spec:
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: POSTGRESQL_PORT_NUMBER
      value: "5432"
    - name: POSTGRESQL_VOLUME_DIR
      value: /bitnami/postgresql
    - name: PGDATA
      value: /bitnami/postgresql/data
    - name: POSTGRES_USER
      value: econsulatbusiness
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: econsulatbusiness-postgresql
    - name: POSTGRES_DB
      value: econsulatBusiness
    image: docker.io/bitnami/postgresql:11.5.0-debian-9-r84
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exec pg_isready -U "econsulatbusiness" -d "econsulatBusiness" -h 127.0.0.1
          -p 5432
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: econsulatbusiness-postgresql
    ports:
    - containerPort: 5432
      name: postgresql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - -e
        - |
          pg_isready -U "econsulatbusiness" -d "econsulatBusiness" -h 127.0.0.1 -p 5432
          [ -f /opt/bitnami/postgresql/tmp/.initialized ]
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/postgresql
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pmvwd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: econsulat-postgresql-0
  initContainers:
  - command:
    - /bin/sh
    - -c
    - |
      mkdir -p /bitnami/postgresql/data
      chmod 700 /bitnami/postgresql/data
      find /bitnami/postgresql -mindepth 0 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs chown -R 1001:1001
    image: docker.io/bitnami/minideb:stretch
    imagePullPolicy: Always
    name: init-chmod-data
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/postgresql
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pmvwd
      readOnly: true
  nodeName: node14859-env-3424666.my.p4d.click
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: default
  serviceAccountName: default
  subdomain: econsulatbusiness-postgresql-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-econsulat-postgresql-0
  - name: kube-api-access-pmvwd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-02T08:59:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T16:11:40Z"
    message: 'containers with unready status: [econsulatbusiness-postgresql]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T16:18:41Z"
    message: 'containers with unready status: [econsulatbusiness-postgresql]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-02T08:59:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f2e062c556d60bf9d92445c4c9ff0fa97850e5610d87a9797bad1c3a6ddfe1ce
    image: docker.io/bitnami/postgresql:11.5.0-debian-9-r84
    imageID: docker.io/bitnami/postgresql@sha256:10c820fa249930bcdcbb98a40c2fa80b797a194ec7b2284ba52ed4cf10f3b851
    lastState: {}
    name: econsulatbusiness-postgresql
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://f2e062c556d60bf9d92445c4c9ff0fa97850e5610d87a9797bad1c3a6ddfe1ce
        exitCode: 255
        finishedAt: "2023-08-25T16:18:31Z"
        reason: Unknown
        startedAt: "2023-08-02T08:59:41Z"
  hostIP: 10.30.4.73
  initContainerStatuses:
  - containerID: containerd://0a4b8457d8704af134aa1e88ad14f93f2873a10b551df40fce01f4a40a6a4733
    image: docker.io/bitnami/minideb:stretch
    imageID: docker.io/bitnami/minideb@sha256:a6f24bce85d037d47cc552635b0f0a3623472bbcf16b33711fb0fe4e6a34480f
    lastState: {}
    name: init-chmod-data
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://0a4b8457d8704af134aa1e88ad14f93f2873a10b551df40fce01f4a40a6a4733
        exitCode: 0
        finishedAt: "2023-08-02T08:59:40Z"
        reason: Completed
        startedAt: "2023-08-02T08:59:40Z"
  phase: Running
  qosClass: Burstable
  startTime: "2023-08-02T08:59:38Z"
